/**
 * @file models/alert.model.js
 * @description Mongoose schema and model for the Alert entity.
 *
 * Alerts are generated by the backend engine when anomalous employee
 * behaviour is detected. They are pushed to the manager dashboard in
 * real time via Socket.IO and stored in MongoDB for the alert log.
 *
 * Alert types:
 *  - MissedCenter  : Employee ended duty without visiting a center (F068)
 *  - TrackingOff   : No GPS ping received for > 5 minutes (F071)
 *  - Idle          : Employee stationary for > N minutes (future)
 *  - LateStart     : Assignment not started by scheduled time (future)
 *  - Deviation     : Employee moved outside expected route corridor (future)
 *
 * Schema overview:
 * ┌────────────────────────────────────────────────────────────────┐
 * │ Alert                                                          │
 * │  companyId       ObjectId  Multi-tenancy scope                 │
 * │  managerId       ObjectId  Manager to notify                   │
 * │  employeeId      ObjectId  Employee who triggered the alert    │
 * │  assignmentId    ObjectId  Related assignment (if applicable)  │
 * │  type            string    Alert category enum                 │
 * │  message         string    Human-readable description          │
 * │  centerId        ObjectId? Center involved (MissedCenter only) │
 * │  centerName      string?   Denormalised for fast display       │
 * │  triggeredAt     Date      When the alert was created          │
 * │  acknowledgedAt  Date?     When manager acknowledged           │
 * │  isAcknowledged  boolean   Read/unread state                   │
 * └────────────────────────────────────────────────────────────────┘
 *
 * Indexes:
 *  - { companyId, triggeredAt }   → manager alert list (primary query)
 *  - { companyId, isAcknowledged} → unread badge count
 *  - { employeeId, triggeredAt }  → per-employee alert history
 *
 * @module models/alert
 */

import mongoose from 'mongoose';

// ─── Constants ────────────────────────────────────────────────────────────────

export const ALERT_TYPES = Object.freeze({
   MISSED_CENTER: 'MissedCenter',
   TRACKING_OFF: 'TrackingOff',
   IDLE: 'Idle',
   LATE_START: 'LateStart',
   DEVIATION: 'Deviation',
});

// ─── Schema ───────────────────────────────────────────────────────────────────

const alertSchema = new mongoose.Schema(
   {
      /** Multi-tenancy scope */
      companyId: {
         type: mongoose.Schema.Types.ObjectId,
         required: [true, 'Company ID is required'],
      },

      /** Manager who should receive this alert */
      managerId: {
         type: mongoose.Schema.Types.ObjectId,
         ref: 'User',
         required: [true, 'Manager ID is required'],
      },

      /** Employee who triggered the alert */
      employeeId: {
         type: mongoose.Schema.Types.ObjectId,
         ref: 'User',
         required: [true, 'Employee ID is required'],
      },

      /** Related assignment (null for TrackingOff when no active assignment) */
      assignmentId: {
         type: mongoose.Schema.Types.ObjectId,
         ref: 'Assignment',
         default: null,
      },

      /** Alert category */
      type: {
         type: String,
         enum: {
            values: Object.values(ALERT_TYPES),
            message: `Alert type must be one of: ${Object.values(ALERT_TYPES).join(', ')}`,
         },
         required: [true, 'Alert type is required'],
      },

      /** Human-readable description shown in the dashboard alert panel */
      message: {
         type: String,
         required: [true, 'Alert message is required'],
         trim: true,
         maxlength: [500, 'Message cannot exceed 500 characters'],
      },

      /**
       * Center involved in the alert — only for MissedCenter type.
       * null for all other alert types.
       */
      centerId: {
         type: mongoose.Schema.Types.ObjectId,
         default: null,
      },

      /** Denormalised center name for fast display without Route join */
      centerName: {
         type: String,
         default: null,
         trim: true,
      },

      /** Authoritative timestamp when the alert was generated */
      triggeredAt: {
         type: Date,
         default: () => new Date(),
      },

      /** Timestamp when the manager acknowledged (read) this alert */
      acknowledgedAt: {
         type: Date,
         default: null,
      },

      /** Whether the manager has acknowledged this alert */
      isAcknowledged: {
         type: Boolean,
         default: false,
      },
   },
   {
      timestamps: false, // triggeredAt serves as createdAt
      versionKey: false,
   },
);

// ─── Indexes ──────────────────────────────────────────────────────────────────

/** Primary manager alert list: company + newest first */
alertSchema.index({ companyId: 1, triggeredAt: -1 });

/** Unread badge count query */
alertSchema.index({ companyId: 1, isAcknowledged: 1 });

/** Per-employee alert history */
alertSchema.index({ employeeId: 1, triggeredAt: -1 });

// ─── Static Methods ───────────────────────────────────────────────────────────

/**
 * Creates and saves an alert document.
 * Centralised helper used by all alert generators.
 *
 * @param {{
 *   companyId: string,
 *   managerId: string,
 *   employeeId: string,
 *   assignmentId?: string,
 *   type: string,
 *   message: string,
 *   centerId?: string,
 *   centerName?: string,
 * }} data
 * @returns {Promise<import('mongoose').Document>}
 */
alertSchema.statics.createAlert = async function (data) {
   return this.create({
      companyId: data.companyId,
      managerId: data.managerId,
      employeeId: data.employeeId,
      assignmentId: data.assignmentId ?? null,
      type: data.type,
      message: data.message,
      centerId: data.centerId ?? null,
      centerName: data.centerName ?? null,
      triggeredAt: new Date(),
      isAcknowledged: false,
   });
};

// ─── Export ───────────────────────────────────────────────────────────────────

const Alert = mongoose.model('Alert', alertSchema);

export default Alert;
